version: "2.4"
services:
  matomo:
    build: .
    image: olkitu/docker-matomo
    ports:
    - 8080:80
    restart: always
    env_file: .env
    depends_on:
      - db
  db:
    image: mariadb
    ports:
    - 3306:3306
    restart: always
    env_file: .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${MATOMO_DATABASE_DBNAME}
      MYSQL_USER: ${MATOMO_DATABASE_USERNAME}
      MYSQL_PASSWORD: ${MATOMO_DATABASE_PASSWORD}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d