version: "2.4"
services:
  matomo:
    build: .
    image: olkitu/docker-matomo
    ports:
    - 8080:80
    env_file: .env
    depends_on:
      db:
        condition: service_healthy 
  db:
    image: mariadb
    ports:
    - 33067:3306
    env_file: .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${MATOMO_DATABASE_DBNAME}
      MYSQL_USER: ${MATOMO_DATABASE_USERNAME}
      MYSQL_PASSWORD: ${MATOMO_DATABASE_PASSWORD}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - matomo-db:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1

volumes:
  matomo-db: